k8s_yaml(kustomize('kubernetes'))

local_resource(
  'deploy',
  './gradlew build')

docker_build(
  'google-org/call-me-back-backend',
  'backend',
  #live_update = [
   # sync('./build/libs/*.jar', '/usr/app/app.jar'),
    
    # Restart the Docker containers to pick up the changes.
    #restart_container(),
  #]
)

docker_build(
  'google-org/call-me-back-frontend',
  'frontend',
  live_update = [
    sync('./frontend/build.gradle', '/usr/app/'),
    sync('./frontend/settings.gradle', '/usr/app/'),
    sync('./frontend/package.json', '/usr/app/'),
    sync('./frontend/package-lock.json', '/usr/app/'),

    # Restart the Docker containers to pick up the changed files.
    restart_container(),
  ]
)
