server:
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      database: nyst
      authentication-database: admin
    rest:
      base-path: /v1
defaults:
    movingAverage:
        numberOfCalls: 10
        smoothingFactor: 2
