k8s_yaml(kustomize('kubernetes'))

docker_build(
  'google-org/hello-world-redux-backend',
  'backend',
)

docker_build(
  'google-org/hello-world-redux-frontend',
  'frontend',
)

k8s_resource('hwr-frontend', port_forwards=8080)
