# -*- mode: Python -*-

local_resource(
  'backend-compile',
  './gradlew bootJar && ' +
  'unzip -o build/libs/backend-0.0.1-SNAPSHOT.jar -d build/jar-staging && ' +
  'rsync --inplace --checksum -r build/jar-staging/ build/jar',
  deps=['src', 'build.gradle'])

docker_build(
  'backend-image',
  './build/jar',
  dockerfile='./Dockerfile',
  live_update=[
    sync('./build/jar/BOOT-INF/lib', '/app/lib'),
    sync('./build/jar/META-INF', '/app/META-INF'),
    sync('./build/jar/BOOT-INF/classes', '/app'),
  ],
  entrypoint = 'find . | entr -r java -Dspring.profiles.active=k8s -noverify -cp .:./lib/* org.google.callmeback.CallMeBackApp')

k8s_yaml('k8s.yml')
k8s_resource('backend', port_forwards=8000, resource_deps=['backend-compile','database'])
