spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: Person
            authentication-database: admin
            username: root
            password: ABADIDEA
        rest:
            base-path: /api