apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: api
spec:
  clusterIP: None
  ports:
    - port: 27017
  selector:
    app.kubernetes.io/name: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  terminationGracePeriodSeconds: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: database
  serviceName: database-service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: api
    spec:
      containers:
      - name: database
        image: mongo:latest
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: ABADIDEA
          - name: MONGO_INITDB_DATABASE
            value: nyst
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: database-data
            mountPath: /data/db
          - name: database-init
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: database-init
          configMap:
              name: database-config
  volumeClaimTemplates:
  - metadata:
      name: database-data
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
