apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: its
spec:
  ports:
    - port: 3000
  selector:
    app.kubernetes.io/name: app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
        app.kubernetes.io/component: app
        app.kubernetes.io/part-of: its        
    spec:
      containers:
      - name: app
        image: app-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "125Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
