apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: its
spec:
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
      app.kubernetes.io/name: api
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: its        
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: its        
    spec:
      containers:
      - name: api
        image: api-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
