apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: callmeback
spec:
  ports:
    - port: 3000
  selector:
    app.kubernetes.io/name: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: callmeback        
    spec:
      containers:
      - name: frontend
        image: frontend-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "125Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
