server:
  servlet:
    context-path: /api
spring:
    data:
        mongodb:
            authentication-database: admin
        rest:
            base-path: /v1
defaults:
    movingAverage:
        numberOfCalls: 10
        smoothingFactor: 2