server:
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      database: nyst
      authentication-database: admin
    rest:
      base-path: /v1
okta:
  oauth2:
    issuer: "https://login-qa.ny.gov/oauth2/default"
    client-id: "0oa42dahlsB0KMpJF297"
