apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: its
spec:
  ports:
    - port: 3000
  selector:
    app.kubernetes.io/name: web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: its        
    spec:
      containers:
      - name: web
        image: web-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "125Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
