# Start with a base Dockerfile with none of our source code,
# and an entry point that starts a server.

docker_build('web-image', '.',
  live_update=[
    # when package.json changes, we need to do a full build
    fall_back_on(['package.json', 'yarn.lock']),
    # Map the local source code into the container under /src
    sync('.', '/src'),
  ])

k8s_yaml('k8s.yml')
k8s_resource('web', port_forwards=3000, resource_deps=['api'])
